version: "2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es-live
    environment:
      - discovery.type=single-node
    volumes:
      - "${HOME}/pyprojects/data-literature:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
